server:
  port: 6666

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://localhost:3306/smart-admin-dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT

mybatis-plus:
  global-config:
    #主键类型 auto：“数据库id自增”
    id-type: auto
  #配置Mapper映射文件
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-imp: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.smartadmin.master
#
#logging:
#  level:
#    org.springframework.web: debug
#    root: info
#  config: log4j2.xml

