server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: root
    password: 123456
    url: jdbc:p6spy:mysql://localhost:3306/smart-admin-dev?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT

mybatis-plus:
  global-config:
    #主键类型 auto：“数据库id自增”
    id-type: auto
  #配置Mapper映射文件
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    log-imp: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.smartadmin.master

logging:
  level:
    org.springframework.web: info
    root: info
  path: classpath:/${profiles.active}/log4j2.xml

####################swagger2 配置 ##########################
swagger:
  apiGroupName: smartAdmin apiGroupName
  title: smartAdmin title
  description: smartAdmin description
  serviceUrl: http://localhost:8888/smart-admin-api
  switch: ON #swagger功能开关：ON：开启功能 OFF：关闭功能
  base:
    package: com.smartadmin.master.module  #swagger扫描包路径
  api:
    version: v1.0 #api接口版本


######################redisson##############################
#redisson:
#  file: classpath:/${profiles.active}/redisson.yml


